<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class SuppliesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $supplies = [
            ['name' => 'TABLA SHANON OFICIO', 'stock' => 5, 'minimum_stock' => 2, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'JUEGO GEOMETRICO', 'stock' => 3, 'minimum_stock' => 1, 'supply_category_id' => 1, 'measurement_unit_id' => 3],
            ['name' => 'ORGANIZADORES GRANDES DE ESCRITORIO', 'stock' => 2, 'minimum_stock' => 1, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'SEPARADORES DE CARTON', 'stock' => 81, 'minimum_stock' => 5, 'supply_category_id' => 1, 'measurement_unit_id' => 3],
            ['name' => 'TOLLA BLANCA', 'stock' => 23, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'RESALTADOR LILA', 'stock' => 4, 'minimum_stock' => 5, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'CINTA ADHESIVA DOBLE CARA', 'stock' => 1, 'minimum_stock' => 1, 'supply_category_id' => 2, 'measurement_unit_id' => 1],
            ['name' => 'GRAPA INDUSTRIAL', 'stock' => 2, 'minimum_stock' => 1, 'supply_category_id' => 1, 'measurement_unit_id' => 2],
            ['name' => 'MAGA', 'stock' => 15, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'PRUEBA F', 'stock' => 12, 'minimum_stock' => 1, 'supply_category_id' => 3, 'measurement_unit_id' => 1],
            ['name' => 'PRUEBA VFVD', 'stock' => 6, 'minimum_stock' => 1, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'PRUEBA FINAL', 'stock' => 200, 'minimum_stock' => 2, 'supply_category_id' => 3, 'measurement_unit_id' => 1],
            ['name' => 'TORNILLO PARA PASTA PEQUEÑO', 'stock' => 1, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 21],
            ['name' => 'TORNILLO PARA PASTA GRANDE', 'stock' => 1, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 21],
            ['name' => 'TINTA PARA SELLO ROJA', 'stock' => 2, 'minimum_stock' => 1, 'supply_category_id' => 4, 'measurement_unit_id' => 1],
            ['name' => 'TINTA PARA SELLO NEGRA', 'stock' => 2, 'minimum_stock' => 1, 'supply_category_id' => 4, 'measurement_unit_id' => 1],
            ['name' => 'TINTA PARA SELLO DE HULE', 'stock' => 2, 'minimum_stock' => 1, 'supply_category_id' => 4, 'measurement_unit_id' => 1],
            ['name' => 'TINTA NEGRA EN ROLL-ON', 'stock' => 3, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'TIJERA PEQUEÑA', 'stock' => 1, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'TIJERA PARA DISEÑO ZIGZAG', 'stock' => 1, 'minimum_stock' => 1, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'TIJERA GRANDE', 'stock' => 11, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'TAPE PEQUEÑO NORMAL', 'stock' => 20, 'minimum_stock' => 1, 'supply_category_id' => 2, 'measurement_unit_id' => 1],
            ['name' => 'TAPE GRUESO TRANSPARENTE SELLADOR PARA CAJAS', 'stock' => 9, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'TAPE DOBLE CARA', 'stock' => 0, 'minimum_stock' => 2, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'TACTO FACIL-GLICERINA', 'stock' => 7, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'TACHUELAS', 'stock' => 3, 'minimum_stock' => 1, 'supply_category_id' => 1, 'measurement_unit_id' => 2],
            ['name' => 'TABLA SHANON CARTA', 'stock' => 4, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'TABLA CON TAPADERA NEGRA', 'stock' => 8, 'minimum_stock' => 2, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'SOBRE PARA CD´S', 'stock' => 102, 'minimum_stock' => 1, 'supply_category_id' => 5, 'measurement_unit_id' => 2],
            ['name' => 'SOBRE MANILA TAMAÑO CARTA', 'stock' => 500, 'minimum_stock' => 50, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'SOBRE MANILA OFICIO', 'stock' => 350, 'minimum_stock' => 50, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'SOBRE MANILA MEDIA CARTA', 'stock' => 302, 'minimum_stock' => 50, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'SOBRE MANILA EXTRA OFICIO', 'stock' => 681, 'minimum_stock' => 50, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'SOBRE BLANCO PEQUEÑO', 'stock' => 1, 'minimum_stock' => 1, 'supply_category_id' => 1, 'measurement_unit_id' => 2],
            ['name' => 'SOBRE BLANCO MEDIANO', 'stock' => 1, 'minimum_stock' => 1, 'supply_category_id' => 1, 'measurement_unit_id' => 2],
            ['name' => 'SILICON LIQUIDO MEDIANO', 'stock' => 6, 'minimum_stock' => 1, 'supply_category_id' => 2, 'measurement_unit_id' => 22],
            ['name' => 'SILICON EN BARRAS', 'stock' => 60, 'minimum_stock' => 1, 'supply_category_id' => 2, 'measurement_unit_id' => 1],
            ['name' => 'SEPARADORES CON NUMEROS Y LETRAS', 'stock' => 2, 'minimum_stock' => 1, 'supply_category_id' => 1, 'measurement_unit_id' => 3],
            ['name' => 'SEPARADOR DE HOJAS PLASTICO', 'stock' => 92, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 3],
            ['name' => 'SACAPUNTAS', 'stock' => 18, 'minimum_stock' => 5, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'SACAGRAPA', 'stock' => 16, 'minimum_stock' => 5, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'SACABOCADO', 'stock' => 7, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'RESALTADOR VERDE CLARO', 'stock' => 6, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'RESALTADOR ROSA', 'stock' => 12, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'RESALTADOR NARANJA', 'stock' => 15, 'minimum_stock' => 5, 'supply_category_id' => 3, 'measurement_unit_id' => 1],
            ['name' => 'RESALTADOR MORADO', 'stock' => 4, 'minimum_stock' => 1, 'supply_category_id' => 3, 'measurement_unit_id' => 1],
            ['name' => 'RESALTADOR DELGADO VERDE', 'stock' => 7, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'RESALTADOR DELGADO ROSADO', 'stock' => 3, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'RESALTADOR CELESTE', 'stock' => 14, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'RESALTADOR AMARILLO', 'stock' => 11, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'REPUESTO MARCADOR VERDE PIZARRA', 'stock' => 5, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'REPUESTO MARCADOR ROJO PIZARRA', 'stock' => 8, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'REPUESTO MARCADOR NEGRO PIZARRA', 'stock' => 5, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'REPUESTO MARCADOR AZUL PIZARRA', 'stock' => 2, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'REGLETA', 'stock' => 1, 'minimum_stock' => 1, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'REGLAS 30 CM', 'stock' => 7, 'minimum_stock' => 1, 'supply_category_id' => 6, 'measurement_unit_id' => 1],
            ['name' => 'REGLA DE METAL', 'stock' => 3, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'PRENSAPAPELES 32MM', 'stock' => 108, 'minimum_stock' => 25, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'PRENSAPAPELES 19MM', 'stock' => 200, 'minimum_stock' => 25, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'PRENSA PAPEL 51MM', 'stock' => 33, 'minimum_stock' => 25, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'POST-IT PEQUEÑO VARIOS COLORES', 'stock' => 13, 'minimum_stock' => 5, 'supply_category_id' => 1, 'measurement_unit_id' => 3],
            ['name' => 'POST-IT GRANDE VARIOS COLORES', 'stock' => 60, 'minimum_stock' => 5, 'supply_category_id' => 1, 'measurement_unit_id' => 3],
            ['name' => 'PORTAMINAS PILOT', 'stock' => 23, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'PORTA LAPIZ', 'stock' => 0, 'minimum_stock' => 1, 'supply_category_id' => 3, 'measurement_unit_id' => 1],
            ['name' => 'PORTA CLIP', 'stock' => 9, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'PISTOLA SILICÓN (PEQUEÑA)', 'stock' => 3, 'minimum_stock' => 1, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'PINCEL FABER-CASTELL', 'stock' => 0, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'PEGAMENTO PEQUEÑO-PRIT', 'stock' => 11, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 23],
            ['name' => 'PEGAMENTO LIQUIDO PEQUEÑO-PRIT', 'stock' => 3, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 22],
            ['name' => 'PEGAMENTO LIQUIDO GRANDE -PRIT', 'stock' => 3, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 22],
            ['name' => 'PEGAMENTO GRANDE -PRIT', 'stock' => 3, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'PASTA DURA TRANSPARENTE PARA ENGARGOLAR', 'stock' => 3, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 3],
            ['name' => 'PASTA DURA NEGRA PARA ENGARGOLAR', 'stock' => 3, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 3],
            ['name' => 'PAQUETE BATERIAS AAA', 'stock' => 4, 'minimum_stock' => 1, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'PAQUETE BATERIAS AA', 'stock' => 6, 'minimum_stock' => 1, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'PAPEL LUSTRE NEGRO', 'stock' => 30, 'minimum_stock' => 5, 'supply_category_id' => 1, 'measurement_unit_id' => 24],
            ['name' => 'PAPEL LUSTRE COLOR', 'stock' => 20, 'minimum_stock' => 5, 'supply_category_id' => 1, 'measurement_unit_id' => 24],
            ['name' => 'PAPEL LINO CARTA BLANCO', 'stock' => 80, 'minimum_stock' => 5, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'PAPEL CHINA NEGRO', 'stock' => 10, 'minimum_stock' => 5, 'supply_category_id' => 1, 'measurement_unit_id' => 24],
            ['name' => 'PAPEL CHINA NEGRO', 'stock' => 10, 'minimum_stock' => 5, 'supply_category_id' => 1, 'measurement_unit_id' => 24],
            ['name' => 'PAPEL CHINA DORADO', 'stock' => 9, 'minimum_stock' => 5, 'supply_category_id' => 1, 'measurement_unit_id' => 24],
            ['name' => 'PAPEL CHINA COLOR VERDE', 'stock' => 0, 'minimum_stock' => 5, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'PAPEL CHINA COLOR ROSADO', 'stock' => 0, 'minimum_stock' => 5, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'PAPEL CHINA NEGRO', 'stock' => 10, 'minimum_stock' => 5, 'supply_category_id' => 1, 'measurement_unit_id' => 24],
            ['name' => 'PAPEL CHINA COLOR ROJO', 'stock' => 0, 'minimum_stock' => 5, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'PAPEL CHINA COLOR BLANCO', 'stock' => 0, 'minimum_stock' => 5, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'PAPEL CHINA COLOR AZUL', 'stock' => 0, 'minimum_stock' => 5, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'PAPEL CHINA CAFÉ', 'stock' => 9, 'minimum_stock' => 1, 'supply_category_id' => 1, 'measurement_unit_id' => 24],
            ['name' => 'PAPEL CARBON TAMAÑO CARTA', 'stock' => 3, 'minimum_stock' => 1, 'supply_category_id' => 1, 'measurement_unit_id' => 3],
            ['name' => 'PAPEL CHINA NEGRO', 'stock' => 10, 'minimum_stock' => 5, 'supply_category_id' => 1, 'measurement_unit_id' => 24],
            ['name' => 'PAPEL CARBON OFICIO', 'stock' => 9, 'minimum_stock' => 5, 'supply_category_id' => 1, 'measurement_unit_id' => 3],
            ['name' => 'PAPEL CHINA NEGRO', 'stock' => 10, 'minimum_stock' => 5, 'supply_category_id' => 1, 'measurement_unit_id' => 24],
            ['name' => 'PAPEL BOND TAMAÑO OFICIO', 'stock' => 25, 'minimum_stock' => 5, 'supply_category_id' => 1, 'measurement_unit_id' => 5],
            ['name' => 'PAPEL BOND TAMAÑO CARTA', 'stock' => 71, 'minimum_stock' => 5, 'supply_category_id' => 1, 'measurement_unit_id' => 5],
            ['name' => 'PAPEL BOND 11 X 17 PULGADAS', 'stock' => 2, 'minimum_stock' => 1, 'supply_category_id' => 1, 'measurement_unit_id' => 5],
            ['name' => 'PAPEL CHINA NEGRO', 'stock' => 10, 'minimum_stock' => 5, 'supply_category_id' => 1, 'measurement_unit_id' => 24],
            ['name' => 'PAPEL AUTO ADHESIVO KARLA', 'stock' => 40, 'minimum_stock' => 10, 'supply_category_id' => 1, 'measurement_unit_id' => 25],
            ['name' => 'PAPEL ARCOIRIS LISO OFICIO VERDE', 'stock' => 0, 'minimum_stock' => 5, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'PAPEL ARCOIRIS LISO OFICIO ROSADO', 'stock' => 0, 'minimum_stock' => 5, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'PAPEL ARCOIRIS LISO OFICIO CELESTE', 'stock' => 0, 'minimum_stock' => 5, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'PAPEL ARCOIRIS LISO OFICIO AMARILLO', 'stock' => 0, 'minimum_stock' => 5, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'PAPEL ARCOIRIS LISO CARTE VERDE', 'stock' => 0, 'minimum_stock' => 5, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'PAPEL ARCOIRIS CARTA AMARILLO', 'stock' => 0, 'minimum_stock' => 5, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'PAPEL ARCO IRIS VARIOS COLORES', 'stock' => 3, 'minimum_stock' => 5, 'supply_category_id' => 1, 'measurement_unit_id' => 24],
            ['name' => 'PAPEL ADHERIBLE TRANSPARENTE', 'stock' => 37, 'minimum_stock' => 5, 'supply_category_id' => 1, 'measurement_unit_id' => 26],
            ['name' => 'PAPEL ADHERIBLE COLOR NEGRO', 'stock' => 16, 'minimum_stock' => 5, 'supply_category_id' => 1, 'measurement_unit_id' => 26],
            ['name' => 'MOUSE PAD', 'stock' => 3, 'minimum_stock' => 1, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'MOUSE', 'stock' => 9, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'MINA 0.7 mm', 'stock' => 36, 'minimum_stock' => 5, 'supply_category_id' => 1, 'measurement_unit_id' => 27],
            ['name' => 'MINA 0.5 mm', 'stock' => 6, 'minimum_stock' => 5, 'supply_category_id' => 1, 'measurement_unit_id' => 27],
            ['name' => 'MEMORIA USB DE 64 GB', 'stock' => 6, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'MEMORIA USB DE 32 GB', 'stock' => 10, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'MASKING TAPE DE 3 PULGADAS', 'stock' => 7, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'MASKING TAPE 2 PULGADAS', 'stock' => 11, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'MASKING TAPE 1 PULGADA', 'stock' => 9, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'MARCADOR PIZARRA VERDE OSCURO', 'stock' => 5, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'MARCADOR PIZARRA VERDE CLARO', 'stock' => 5, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'MARCADOR PIZARRA ROSA', 'stock' => 0, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'MARCADOR PIZARRA ROJO', 'stock' => 6, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'MARCADOR PIZARRA NEGRO', 'stock' => 9, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'MARCADOR PIZARRA MORADO', 'stock' => 4, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'MARCADOR PIZARRA AZUL', 'stock' => 9, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'MARCADOR PERMANENTE VERDE', 'stock' => 4, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'MARCADOR PERMANENTE ROJO', 'stock' => 6, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'MARCADOR PERMANENTE NEGRO', 'stock' => 15, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'MARCADOR PERMANENTE AZUL', 'stock' => 6, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'MARCADOR PARA CD EDDING PUNTO FINO NEGRO', 'stock' => 6, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'MARCADOR DE PIZARRA DE REPUESTO VERDE', 'stock' => 1, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'MARCADOR DE PIZARRA DE REPUESTO ROJO', 'stock' => 2, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'LUPA', 'stock' => 12, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'LIQUIDO PARA LIMPIAR PIZZARRA', 'stock' => 4, 'minimum_stock' => 1, 'supply_category_id' => 1, 'measurement_unit_id' => 22],
            ['name' => 'LIBRO DE ACTAS', 'stock' => 0, 'minimum_stock' => 1, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'LIBRETAS DE TAQUIGRAFIA PEQUEÑA', 'stock' => 13, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'LIBRETA NEGRA PEQUEÑA CON LINEAS', 'stock' => 6, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'LEITZ TAMAÑO OFICIO', 'stock' => 62, 'minimum_stock' => 10, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'LEITZ TAMAÑO CARTA', 'stock' => 0, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'LÁPIZ MONGOL', 'stock' => 39, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'LAPICEROS LIC MANUEL', 'stock' => 18, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'LAPICERO PILOT GEL COLOR ROJO 0.5', 'stock' => 16, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'LAPICERO PILOT GEL COLOR NEGRO 0.5/0.7', 'stock' => 32, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'LAPICERO PILOT GEL COLOR AZUL 0.5/0.7', 'stock' => 35, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'LAPICERO PILOT FINE COLOR VERDE', 'stock' => 4, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'LAPICERO PILOT FINE COLOR ROSADO', 'stock' => 9, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'LAPICERO PILOT FINE COLOR ROJO', 'stock' => 26, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'LAPICERO PILOT FINE COLOR NEGRO', 'stock' => 78, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'LAPICERO PILOT FINE COLOR AZUL', 'stock' => 46, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'LAPICERO CON BASE- PARA RECEPCIÓN', 'stock' => 1, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'HULES', 'stock' => 3, 'minimum_stock' => 1, 'supply_category_id' => 1, 'measurement_unit_id' => 21],
            ['name' => 'HOJAS PROTECTORAS OFICIO', 'stock' => 200, 'minimum_stock' => 25, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'HOJAS PROTECTORAS', 'stock' => 250, 'minimum_stock' => 25, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'HOJAS PAPEL ARCOIRIS', 'stock' => 75, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'GRAPAS NORMALES', 'stock' => 9, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 2],
            ['name' => 'GRAPA ESPECIAL -ENGRAPADORA GRANDE', 'stock' => 0, 'minimum_stock' => 1, 'supply_category_id' => 1, 'measurement_unit_id' => 2],
            ['name' => 'FOLDER PLASTICO (OFICIO) NEGRO', 'stock' => 43, 'minimum_stock' => 5, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'FOLDER PLASTICO (CARTA) NEGRO', 'stock' => 100, 'minimum_stock' => 5, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'FOLDER MANILA (OFICIO)', 'stock' => 751, 'minimum_stock' => 25, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'FOLDER MANILA (CARTA)', 'stock' => 253, 'minimum_stock' => 25, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'FOLDER ESPAÑOL', 'stock' => 12, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'FOAMY VERDE OSCURO', 'stock' => 0, 'minimum_stock' => 5, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'FOAMY VERDE CLARO', 'stock' => 33, 'minimum_stock' => 5, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'FOAMY NARANJA', 'stock' => 0, 'minimum_stock' => 5, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'FOAMY COLOR ROJO', 'stock' => 62, 'minimum_stock' => 5, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'FOAMY COLOR PIEL', 'stock' => 14, 'minimum_stock' => 5, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'FOAMY COLOR NEGRO', 'stock' => 14, 'minimum_stock' => 5, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'FOAMY COLOR MELON', 'stock' => 11, 'minimum_stock' => 5, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'FOAMY COLOR MARRON', 'stock' => 4, 'minimum_stock' => 5, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'FOAMY COLOR CAFÉ', 'stock' => 25, 'minimum_stock' => 5, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'FOAMY COLOR BLANCO', 'stock' => 39, 'minimum_stock' => 5, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'FOAMY COLOR AZUL', 'stock' => 13, 'minimum_stock' => 5, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'FOAMY COLOR AMARILLO', 'stock' => 46, 'minimum_stock' => 5, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'FOAMY CELESTE', 'stock' => 13, 'minimum_stock' => 5, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'FLECHAS GRUESAS', 'stock' => 20, 'minimum_stock' => 5, 'supply_category_id' => 1, 'measurement_unit_id' => 3],
            ['name' => 'FLECHAS DELGADAS', 'stock' => 21, 'minimum_stock' => 5, 'supply_category_id' => 1, 'measurement_unit_id' => 3],
            ['name' => 'FASTENER', 'stock' => 700, 'minimum_stock' => 50, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'ETIQUETAS VERDES (PESTAÑAS)', 'stock' => 1, 'minimum_stock' => 1, 'supply_category_id' => 1, 'measurement_unit_id' => 3],
            ['name' => 'ETIQUETAS TRANSPARENTES (PESTAÑAS)', 'stock' => 0, 'minimum_stock' => 1, 'supply_category_id' => 1, 'measurement_unit_id' => 3],
            ['name' => 'ETIQUETAS ROJAS (PESTAÑAS)', 'stock' => 11, 'minimum_stock' => 1, 'supply_category_id' => 1, 'measurement_unit_id' => 3],
            ['name' => 'ETIQUETAS AZULES (PESTAÑAS)', 'stock' => 4, 'minimum_stock' => 1, 'supply_category_id' => 1, 'measurement_unit_id' => 3],
            ['name' => 'ETIQUETAS ANARANJADAS (PESTAÑAS)', 'stock' => 1, 'minimum_stock' => 1, 'supply_category_id' => 1, 'measurement_unit_id' => 3],
            ['name' => 'ETIQUETAS AMARILLAS (PESTAÑAS)', 'stock' => 10, 'minimum_stock' => 1, 'supply_category_id' => 1, 'measurement_unit_id' => 3],
            ['name' => 'ESPIRAL FAST DE ANILLOS (38 ANILLOS) 8MM (5/16) NEGRO', 'stock' => 306, 'minimum_stock' => 10, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'ESPIRAL FAST DE ANILLOS (38 ANILLOS) 25MM (1) NEGRO', 'stock' => 100, 'minimum_stock' => 10, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'ESPIRAL FAST DE ANILLOS (38 ANILLOS) 22MM (7/8) NEGRO', 'stock' => 25, 'minimum_stock' => 10, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => '5 ESPIRAL FAST DE ANILLOS (38 ANILLOS) 19MM (3/4) NEGRO', 'stock' => 250, 'minimum_stock' => 10, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'ESPIRAL FAST DE ANILLOS (38 ANILLOS) 16MM (5/8) NEGRO', 'stock' => 100, 'minimum_stock' => 10, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'ESPIRAL FAST DE ANILLOS (38 ANILLOS) 14MM (9/16) NEGRO', 'stock' => 50, 'minimum_stock' => 10, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'ESPIRAL FAST DE ANILLOS (38 ANILLOS) EXTRAGRANDE NEGRO', 'stock' => 12, 'minimum_stock' => 10, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'ESPIRAL DE PLASTICO FINO DE 18', 'stock' => 60, 'minimum_stock' => 10, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'ESPIRAL DE PLASTICO FINO 8MM 5/6 NEGRO', 'stock' => 100, 'minimum_stock' => 10, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'ESPIRAL DE PLASTICO FINO DE 20', 'stock' => 34, 'minimum_stock' => 10, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'ENGRAPADORA MEDIANA', 'stock' => 3, 'minimum_stock' => 1, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'ENGRAPADORA GRANDE', 'stock' => 9, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'CUCHILLAS', 'stock' => 2, 'minimum_stock' => 1, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'CUADERNO ESPIRAL PASTA SUAVE', 'stock' => 5, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'CUADERNO ESPIRAL PASTA DURA', 'stock' => 8, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'CRAYON BI- COLOR FABER-CASTELL', 'stock' => 66, 'minimum_stock' => 5, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'CORRECTORES TIPO PLUMÓN', 'stock' => 12, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'CORRECTOR CON BROCHA', 'stock' => 3, 'minimum_stock' => 1, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'CLIP STANDARD', 'stock' => 19, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 2],
            ['name' => 'CLIP MARIPOSA PEQUEÑO', 'stock' => 48, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'CLIP MARIPOSA MEDIANA', 'stock' => 12, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'CLIP GRANDE', 'stock' => 38, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 2],
            ['name' => 'CINTA PARA MARCADOR - FRASCO', 'stock' => 2, 'minimum_stock' => 1, 'supply_category_id' => 1, 'measurement_unit_id' => 28],
            ['name' => 'CINTA PARA MAQUINA IBM', 'stock' => 6, 'minimum_stock' => 1, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'CINTA PARA MAQUINA', 'stock' => 4, 'minimum_stock' => 1, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'CINTA MAQUINA ELECTRICA', 'stock' => 2, 'minimum_stock' => 1, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'CINTA MAGICA-SCOTCH', 'stock' => 24, 'minimum_stock' => 5, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'CDS', 'stock' => 70, 'minimum_stock' => 25, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'CARTUCHO DE TINTA COLORES PARA HP', 'stock' => 0, 'minimum_stock' => 1, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'CARGADOR DE BATERIA MARCA STEREN', 'stock' => 1, 'minimum_stock' => 1, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'CALCULADORA GRANDE-CASIO', 'stock' => 2, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'CALCULADORA CASIO PEQUEÑA', 'stock' => 5, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'BOTE DE SILICON FRIO GRANDE', 'stock' => 4, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'BORRADORES', 'stock' => 11, 'minimum_stock' => 5, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'BORRADOR CON ESCOBITA', 'stock' => 6, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'BORRADOR BOLIGAFO', 'stock' => 8, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'BOLSAS (CARPETA PLASTICA)', 'stock' => 2, 'minimum_stock' => 1, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'BOLSA KRAFT 8 LIBRAS', 'stock' => 53, 'minimum_stock' => 10, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'BLOCK PAPEL DE CONSTRUCCIÓN', 'stock' => 46, 'minimum_stock' => 25, 'supply_category_id' => 1, 'measurement_unit_id' => 29],
            ['name' => 'BLOCK HOJAS MILIMETRADAS', 'stock' => 10, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'BLOCK HOJAS BLANCAS LINEAS', 'stock' => 10, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 29],
            ['name' => 'BLOCK HOJAS AMARILLAS LINEAS', 'stock' => 11, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 29],
            ['name' => 'BLOCK DE NOTAS CON LINEAS AMARILLO OFICIO', 'stock' => 3, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'BASE PARA TAPE', 'stock' => 6, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'ALMOHADILLAS DE SELLOS', 'stock' => 13, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'ALMOHADILLA PARA PIZARRA-AMARILLA', 'stock' => 3, 'minimum_stock' => 1, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
            ['name' => 'ACORDEON', 'stock' => 5, 'minimum_stock' => 3, 'supply_category_id' => 1, 'measurement_unit_id' => 1],
        ];
         foreach ($supplies as $supply) {
            DB::table('supplies')->insert([
                'name' => $supply['name'],
                'description' => null, // Or provide a default description if available
                'stock' => $supply['stock'],
                'minimum_stock' => $supply['minimum_stock'],
                'provider_id' => null, // Set to null as it's nullable and not provided in your array example
                'supply_category_id' => $supply['supply_category_id'],
                'measurement_unit_id' => $supply['measurement_unit_id'],
                'state' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
